
version: '3.8'

services:
  app:
    restart: on-failure
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    build: .
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
